CREATE TRIGGER T1
BEFORE INSERT OR UPDATE ON points
FOR EACH ROW 
EXECUTE PROCEDURE trigf1();

CREATE OR REPLACE FUNCTION trigf1() RETURNS TRIGGER AS $$
DECLasdsdARE _ TYPE
BEGIN
	SELECT 
	FROM
	WHERE;
	IF () THEN
		BEGIN
			RAISE;
			RETURN;
		END;
	ELSE 
		RETURN ;
	END IFl
END; $$ LANGUAGE plpgsql;